-- Catalog: categories, brands, sellers, products, variants, inventory and product content.

CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT REFERENCES categories (id) ON DELETE RESTRICT,
    name        VARCHAR(100) NOT NULL,
    slug        VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(500),
    image_url   VARCHAR(512),
    icon        VARCHAR(40),
    tax_rate    NUMERIC(5, 2) NOT NULL DEFAULT 18.00,
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_categories_tax_rate CHECK (tax_rate >= 0 AND tax_rate <= 40),
    CONSTRAINT ck_categories_not_self_parent CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE INDEX ix_categories_parent ON categories (parent_id);

CREATE TABLE brands
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    slug        VARCHAR(120) NOT NULL UNIQUE,
    logo_url    VARCHAR(512),
    description VARCHAR(500),
    featured    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_brands_name ON brands (lower(name));

CREATE TABLE sellers
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL UNIQUE REFERENCES users (id) ON DELETE RESTRICT,
    store_name     VARCHAR(120) NOT NULL,
    slug           VARCHAR(140) NOT NULL UNIQUE,
    description    VARCHAR(1000),
    logo_url       VARCHAR(512),
    gstin          VARCHAR(15),
    support_email  VARCHAR(254),
    support_phone  VARCHAR(20),
    pickup_line1   VARCHAR(200),
    pickup_city    VARCHAR(80),
    pickup_state   VARCHAR(80),
    pickup_pincode VARCHAR(10),
    status         VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    status_reason  VARCHAR(500),
    rating_average NUMERIC(3, 2) NOT NULL DEFAULT 0,
    rating_count   INTEGER      NOT NULL DEFAULT 0,
    approved_at    TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_sellers_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED'))
);

CREATE INDEX ix_sellers_status ON sellers (status);

-- Products carry denormalized listing fields (min price, rating, stock, sales) that are kept in
-- sync by the application so listing and search pages never aggregate at read time.
CREATE TABLE products
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id          BIGINT        NOT NULL REFERENCES sellers (id) ON DELETE RESTRICT,
    category_id        BIGINT        NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
    brand_id           BIGINT REFERENCES brands (id) ON DELETE SET NULL,
    title              VARCHAR(200)  NOT NULL,
    slug               VARCHAR(220)  NOT NULL UNIQUE,
    short_description  VARCHAR(500),
    description        TEXT,
    highlights         JSONB         NOT NULL DEFAULT '[]',
    tags               VARCHAR(500),
    status             VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
    featured           BOOLEAN       NOT NULL DEFAULT FALSE,
    min_price          NUMERIC(12, 2) NOT NULL DEFAULT 0,
    min_mrp            NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount_percent   INTEGER       NOT NULL DEFAULT 0,
    rating_average     NUMERIC(3, 2) NOT NULL DEFAULT 0,
    rating_count       INTEGER       NOT NULL DEFAULT 0,
    total_stock        INTEGER       NOT NULL DEFAULT 0,
    sold_count         INTEGER       NOT NULL DEFAULT 0,
    view_count         BIGINT        NOT NULL DEFAULT 0,
    warranty           VARCHAR(200),
    returnable         BOOLEAN       NOT NULL DEFAULT TRUE,
    return_window_days INTEGER       NOT NULL DEFAULT 7,
    cod_available      BOOLEAN       NOT NULL DEFAULT TRUE,
    model_url          VARCHAR(512),
    ar_model_url       VARCHAR(512),
    model_poster_url   VARCHAR(512),
    search_keywords    VARCHAR(1000),
    published_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version            BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ck_products_status CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_products_discount CHECK (discount_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_products_return_window CHECK (return_window_days BETWEEN 0 AND 90),
    CONSTRAINT ck_products_counters CHECK (rating_count >= 0 AND total_stock >= 0 AND sold_count >= 0)
);

CREATE INDEX ix_products_seller ON products (seller_id);
CREATE INDEX ix_products_category_status ON products (category_id, status);
CREATE INDEX ix_products_brand ON products (brand_id);
CREATE INDEX ix_products_status_published ON products (status, published_at DESC);
CREATE INDEX ix_products_status_sold ON products (status, sold_count DESC);
CREATE INDEX ix_products_status_price ON products (status, min_price);
CREATE INDEX ix_products_status_discount ON products (status, discount_percent DESC);
CREATE INDEX ix_products_featured ON products (featured) WHERE featured;

-- Selectable option dimensions for a product, e.g. Color / Storage / Size.
-- option_values: [{"value": "Midnight", "swatch": "#1f2937"}, ...]
CREATE TABLE product_attributes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT      NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    name          VARCHAR(40) NOT NULL,
    position      INTEGER     NOT NULL DEFAULT 0,
    option_values JSONB       NOT NULL DEFAULT '[]',
    CONSTRAINT ux_product_attributes_name UNIQUE (product_id, name)
);

-- options: {"Color": "Midnight", "Storage": "128 GB"}
CREATE TABLE product_variants
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   BIGINT        NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    sku          VARCHAR(64)   NOT NULL UNIQUE,
    name         VARCHAR(160)  NOT NULL,
    options      JSONB         NOT NULL DEFAULT '{}',
    price        NUMERIC(12, 2) NOT NULL,
    mrp          NUMERIC(12, 2) NOT NULL,
    weight_grams INTEGER,
    is_default   BOOLEAN       NOT NULL DEFAULT FALSE,
    active       BOOLEAN       NOT NULL DEFAULT TRUE,
    position     INTEGER       NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version      BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ck_product_variants_price CHECK (price > 0 AND mrp >= price)
);

CREATE INDEX ix_product_variants_product ON product_variants (product_id);

-- Stock is reserved when an order is placed and committed or released when payment settles.
CREATE TABLE inventory
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id          BIGINT      NOT NULL UNIQUE REFERENCES product_variants (id) ON DELETE CASCADE,
    quantity_available  INTEGER     NOT NULL DEFAULT 0,
    quantity_reserved   INTEGER     NOT NULL DEFAULT 0,
    low_stock_threshold INTEGER     NOT NULL DEFAULT 5,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    version             BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT ck_inventory_non_negative CHECK (quantity_available >= 0 AND quantity_reserved >= 0)
);

CREATE TABLE product_images
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    variant_id BIGINT REFERENCES product_variants (id) ON DELETE SET NULL,
    url        VARCHAR(512) NOT NULL,
    alt_text   VARCHAR(200),
    position   INTEGER      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_product_images_product ON product_images (product_id, position);

CREATE TABLE product_specifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    group_name VARCHAR(60)  NOT NULL DEFAULT 'General',
    name       VARCHAR(80)  NOT NULL,
    value      VARCHAR(500) NOT NULL,
    position   INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX ix_product_specifications_product ON product_specifications (product_id, position);

-- Customer questions answered by the seller on the product page.
CREATE TABLE product_questions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT        NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    user_id     BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    question    VARCHAR(500)  NOT NULL,
    answer      VARCHAR(1000),
    answered_by BIGINT REFERENCES users (id) ON DELETE SET NULL,
    answered_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX ix_product_questions_product ON product_questions (product_id, created_at DESC);
