-- Commerce: carts, wishlists, coupons, orders, shipments, payments, returns and refunds.

CREATE TABLE carts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    coupon_code VARCHAR(40),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    version     BIGINT      NOT NULL DEFAULT 0
);

CREATE TABLE cart_items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id         BIGINT        NOT NULL REFERENCES carts (id) ON DELETE CASCADE,
    variant_id      BIGINT        NOT NULL REFERENCES product_variants (id) ON DELETE CASCADE,
    quantity        INTEGER       NOT NULL,
    saved_for_later BOOLEAN       NOT NULL DEFAULT FALSE,
    price_at_add    NUMERIC(12, 2) NOT NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ux_cart_items_variant UNIQUE (cart_id, variant_id),
    CONSTRAINT ck_cart_items_quantity CHECK (quantity BETWEEN 1 AND 10)
);

CREATE INDEX ix_cart_items_variant ON cart_items (variant_id);

CREATE TABLE wishlists
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE wishlist_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wishlist_id  BIGINT        NOT NULL REFERENCES wishlists (id) ON DELETE CASCADE,
    product_id   BIGINT        NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    variant_id   BIGINT REFERENCES product_variants (id) ON DELETE SET NULL,
    price_at_add NUMERIC(12, 2) NOT NULL,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ux_wishlist_items_product UNIQUE (wishlist_id, product_id)
);

CREATE INDEX ix_wishlist_items_product ON wishlist_items (product_id);

CREATE TABLE coupons
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(40)   NOT NULL,
    description     VARCHAR(255)  NOT NULL,
    discount_type   VARCHAR(12)   NOT NULL,
    discount_value  NUMERIC(12, 2) NOT NULL,
    min_order_value NUMERIC(12, 2) NOT NULL DEFAULT 0,
    max_discount    NUMERIC(12, 2),
    starts_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ,
    usage_limit     INTEGER,
    per_user_limit  INTEGER       NOT NULL DEFAULT 1,
    used_count      INTEGER       NOT NULL DEFAULT 0,
    scope           VARCHAR(12)   NOT NULL DEFAULT 'ALL',
    user_specific   BOOLEAN       NOT NULL DEFAULT FALSE,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version         BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ck_coupons_type CHECK (discount_type IN ('PERCENTAGE', 'FIXED')),
    CONSTRAINT ck_coupons_value CHECK (discount_value > 0 AND (discount_type <> 'PERCENTAGE' OR discount_value <= 90)),
    CONSTRAINT ck_coupons_scope CHECK (scope IN ('ALL', 'CATEGORY', 'PRODUCT')),
    CONSTRAINT ck_coupons_limits CHECK (per_user_limit > 0 AND (usage_limit IS NULL OR usage_limit > 0)),
    CONSTRAINT ck_coupons_window CHECK (expires_at IS NULL OR expires_at > starts_at)
);

CREATE UNIQUE INDEX ux_coupons_code ON coupons (upper(code));

CREATE TABLE coupon_categories
(
    coupon_id   BIGINT NOT NULL REFERENCES coupons (id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    PRIMARY KEY (coupon_id, category_id)
);

CREATE TABLE coupon_products
(
    coupon_id  BIGINT NOT NULL REFERENCES coupons (id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    PRIMARY KEY (coupon_id, product_id)
);

CREATE TABLE coupon_users
(
    coupon_id BIGINT NOT NULL REFERENCES coupons (id) ON DELETE CASCADE,
    user_id   BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (coupon_id, user_id)
);

-- Orders snapshot the shipping address and all prices at placement time so later catalog or
-- address edits never rewrite purchase history.
CREATE TABLE orders
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number            VARCHAR(24)   NOT NULL UNIQUE,
    user_id                 BIGINT        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    status                  VARCHAR(24)   NOT NULL,
    payment_method          VARCHAR(16)   NOT NULL,
    payment_status          VARCHAR(20)   NOT NULL,
    delivery_option         VARCHAR(16)   NOT NULL DEFAULT 'STANDARD',
    ship_name               VARCHAR(120)  NOT NULL,
    ship_phone              VARCHAR(20)   NOT NULL,
    ship_line1              VARCHAR(200)  NOT NULL,
    ship_line2              VARCHAR(200),
    ship_landmark           VARCHAR(120),
    ship_city               VARCHAR(80)   NOT NULL,
    ship_state              VARCHAR(80)   NOT NULL,
    ship_pincode            VARCHAR(10)   NOT NULL,
    ship_country            VARCHAR(2)    NOT NULL DEFAULT 'IN',
    item_count              INTEGER       NOT NULL,
    mrp_total               NUMERIC(12, 2) NOT NULL,
    subtotal                NUMERIC(12, 2) NOT NULL,
    coupon_code             VARCHAR(40),
    coupon_discount         NUMERIC(12, 2) NOT NULL DEFAULT 0,
    shipping_fee            NUMERIC(12, 2) NOT NULL DEFAULT 0,
    cod_fee                 NUMERIC(12, 2) NOT NULL DEFAULT 0,
    tax_amount              NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_amount            NUMERIC(12, 2) NOT NULL,
    refunded_amount         NUMERIC(12, 2) NOT NULL DEFAULT 0,
    currency                VARCHAR(3)    NOT NULL DEFAULT 'INR',
    estimated_delivery_date DATE,
    idempotency_key         VARCHAR(64),
    placed_at               TIMESTAMPTZ   NOT NULL DEFAULT now(),
    confirmed_at            TIMESTAMPTZ,
    delivered_at            TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    cancel_reason           VARCHAR(255),
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version                 BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ck_orders_status CHECK (status IN ('PENDING_PAYMENT', 'PLACED', 'CONFIRMED', 'PROCESSING', 'SHIPPED',
                                                  'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'PAYMENT_FAILED',
                                                  'RETURNED')),
    CONSTRAINT ck_orders_payment_method CHECK (payment_method IN ('UPI', 'CARD', 'NETBANKING', 'WALLET', 'COD')),
    CONSTRAINT ck_orders_payment_status CHECK (payment_status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED',
                                                                  'PARTIALLY_REFUNDED')),
    CONSTRAINT ck_orders_delivery_option CHECK (delivery_option IN ('STANDARD', 'EXPRESS')),
    CONSTRAINT ck_orders_amounts CHECK (total_amount >= 0 AND refunded_amount >= 0 AND refunded_amount <= total_amount)
);

CREATE INDEX ix_orders_user_placed ON orders (user_id, placed_at DESC);
CREATE INDEX ix_orders_status ON orders (status);
CREATE INDEX ix_orders_placed_at ON orders (placed_at);
CREATE UNIQUE INDEX ux_orders_idempotency ON orders (user_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE TABLE order_status_history
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT      NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    status     VARCHAR(24) NOT NULL,
    note       VARCHAR(255),
    actor_id   BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_order_status_history_order ON order_status_history (order_id, created_at);

-- One shipment per seller per order; each seller fulfils their own items.
CREATE TABLE shipments
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                BIGINT      NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    seller_id               BIGINT      NOT NULL REFERENCES sellers (id) ON DELETE RESTRICT,
    shipment_number         VARCHAR(24) NOT NULL UNIQUE,
    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    carrier                 VARCHAR(60),
    tracking_number         VARCHAR(60),
    estimated_delivery_date DATE,
    processing_at           TIMESTAMPTZ,
    shipped_at              TIMESTAMPTZ,
    out_for_delivery_at     TIMESTAMPTZ,
    delivered_at            TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    version                 BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT ck_shipments_status CHECK (status IN ('PENDING', 'PROCESSING', 'SHIPPED', 'OUT_FOR_DELIVERY',
                                                     'DELIVERED', 'CANCELLED'))
);

CREATE INDEX ix_shipments_order ON shipments (order_id);
CREATE INDEX ix_shipments_seller_status ON shipments (seller_id, status, created_at DESC);

CREATE TABLE shipment_events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT       NOT NULL REFERENCES shipments (id) ON DELETE CASCADE,
    status      VARCHAR(20)  NOT NULL,
    location    VARCHAR(120),
    description VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_shipment_events_shipment ON shipment_events (shipment_id, occurred_at);

CREATE TABLE order_items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT        NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    shipment_id     BIGINT REFERENCES shipments (id) ON DELETE SET NULL,
    product_id      BIGINT        NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
    variant_id      BIGINT        NOT NULL REFERENCES product_variants (id) ON DELETE RESTRICT,
    seller_id       BIGINT        NOT NULL REFERENCES sellers (id) ON DELETE RESTRICT,
    product_title   VARCHAR(200)  NOT NULL,
    variant_name    VARCHAR(160),
    sku             VARCHAR(64)   NOT NULL,
    image_url       VARCHAR(512),
    unit_price      NUMERIC(12, 2) NOT NULL,
    unit_mrp        NUMERIC(12, 2) NOT NULL,
    quantity        INTEGER       NOT NULL,
    tax_rate        NUMERIC(5, 2) NOT NULL,
    line_total      NUMERIC(12, 2) NOT NULL,
    coupon_discount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    status          VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_items_status CHECK (status IN ('ACTIVE', 'CANCELLED', 'RETURN_REQUESTED', 'RETURNED'))
);

CREATE INDEX ix_order_items_order ON order_items (order_id);
CREATE INDEX ix_order_items_shipment ON order_items (shipment_id);
CREATE INDEX ix_order_items_seller ON order_items (seller_id, created_at DESC);
CREATE INDEX ix_order_items_product ON order_items (product_id);
CREATE INDEX ix_order_items_variant ON order_items (variant_id);

CREATE TABLE payments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT        NOT NULL REFERENCES orders (id) ON DELETE RESTRICT,
    user_id             BIGINT        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    provider            VARCHAR(16)   NOT NULL,
    method              VARCHAR(16)   NOT NULL,
    status              VARCHAR(20)   NOT NULL DEFAULT 'CREATED',
    amount              NUMERIC(12, 2) NOT NULL,
    currency            VARCHAR(3)    NOT NULL DEFAULT 'INR',
    provider_order_id   VARCHAR(64),
    provider_payment_id VARCHAR(64),
    failure_reason      VARCHAR(255),
    paid_at             TIMESTAMPTZ,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version             BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ck_payments_provider CHECK (provider IN ('RAZORPAY', 'SANDBOX', 'COD')),
    CONSTRAINT ck_payments_status CHECK (status IN ('CREATED', 'CAPTURED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED')),
    CONSTRAINT ck_payments_amount CHECK (amount >= 0)
);

CREATE INDEX ix_payments_order ON payments (order_id);
CREATE INDEX ix_payments_status_created ON payments (status, created_at DESC);
CREATE UNIQUE INDEX ux_payments_provider_order ON payments (provider, provider_order_id) WHERE provider_order_id IS NOT NULL;
CREATE UNIQUE INDEX ux_payments_provider_payment ON payments (provider, provider_payment_id) WHERE provider_payment_id IS NOT NULL;

CREATE TABLE return_requests
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_number   VARCHAR(24)   NOT NULL UNIQUE,
    order_id        BIGINT        NOT NULL REFERENCES orders (id) ON DELETE RESTRICT,
    order_item_id   BIGINT        NOT NULL REFERENCES order_items (id) ON DELETE RESTRICT,
    user_id         BIGINT        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    seller_id       BIGINT        NOT NULL REFERENCES sellers (id) ON DELETE RESTRICT,
    quantity        INTEGER       NOT NULL,
    reason          VARCHAR(40)   NOT NULL,
    comments        VARCHAR(1000),
    status          VARCHAR(20)   NOT NULL DEFAULT 'REQUESTED',
    refund_amount   NUMERIC(12, 2) NOT NULL,
    resolution_note VARCHAR(500),
    resolved_by     BIGINT,
    resolved_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version         BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ck_return_requests_status CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'PICKED_UP', 'REFUNDED')),
    CONSTRAINT ck_return_requests_reason CHECK (reason IN ('DAMAGED', 'DEFECTIVE', 'WRONG_ITEM', 'NOT_AS_DESCRIBED',
                                                           'SIZE_FIT', 'CHANGED_MIND', 'OTHER')),
    CONSTRAINT ck_return_requests_quantity CHECK (quantity > 0)
);

CREATE INDEX ix_return_requests_user ON return_requests (user_id, created_at DESC);
CREATE INDEX ix_return_requests_seller_status ON return_requests (seller_id, status);
-- An order item can only have one open (non-rejected) return.
CREATE UNIQUE INDEX ux_return_requests_open_item ON return_requests (order_item_id) WHERE status <> 'REJECTED';

CREATE TABLE refunds
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_number      VARCHAR(24)   NOT NULL UNIQUE,
    order_id           BIGINT        NOT NULL REFERENCES orders (id) ON DELETE RESTRICT,
    payment_id         BIGINT REFERENCES payments (id) ON DELETE RESTRICT,
    return_request_id  BIGINT REFERENCES return_requests (id) ON DELETE SET NULL,
    amount             NUMERIC(12, 2) NOT NULL,
    status             VARCHAR(16)   NOT NULL DEFAULT 'PENDING',
    provider_refund_id VARCHAR(64),
    reason             VARCHAR(255)  NOT NULL,
    failure_reason     VARCHAR(255),
    processed_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_refunds_status CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED')),
    CONSTRAINT ck_refunds_amount CHECK (amount > 0)
);

CREATE INDEX ix_refunds_order ON refunds (order_id);
CREATE INDEX ix_refunds_status ON refunds (status, created_at DESC);

CREATE TABLE coupon_redemptions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id       BIGINT        NOT NULL REFERENCES coupons (id) ON DELETE CASCADE,
    user_id         BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    order_id        BIGINT        NOT NULL UNIQUE REFERENCES orders (id) ON DELETE CASCADE,
    discount_amount NUMERIC(12, 2) NOT NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX ix_coupon_redemptions_coupon_user ON coupon_redemptions (coupon_id, user_id);

-- Operator-tunable settings (shipping fees, COD rules, ...), editable from the admin console.
CREATE TABLE platform_settings
(
    key         VARCHAR(60)  PRIMARY KEY,
    value       VARCHAR(500) NOT NULL,
    description VARCHAR(255),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
