-- Engagement: reviews, notifications, search history and browsing history.

CREATE TABLE reviews
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT      NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    user_id           BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    rating            INTEGER     NOT NULL,
    title             VARCHAR(120),
    body              VARCHAR(4000),
    verified_purchase BOOLEAN     NOT NULL DEFAULT FALSE,
    status            VARCHAR(16) NOT NULL DEFAULT 'PUBLISHED',
    helpful_count     INTEGER     NOT NULL DEFAULT 0,
    not_helpful_count INTEGER     NOT NULL DEFAULT 0,
    moderation_note   VARCHAR(500),
    moderated_by      BIGINT,
    moderated_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    version           BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT ux_reviews_product_user UNIQUE (product_id, user_id),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_reviews_status CHECK (status IN ('PUBLISHED', 'PENDING', 'REJECTED')),
    CONSTRAINT ck_reviews_votes CHECK (helpful_count >= 0 AND not_helpful_count >= 0)
);

CREATE INDEX ix_reviews_product_status ON reviews (product_id, status, created_at DESC);
CREATE INDEX ix_reviews_status_created ON reviews (status, created_at DESC);
CREATE INDEX ix_reviews_user ON reviews (user_id);

CREATE TABLE review_images
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT       NOT NULL REFERENCES reviews (id) ON DELETE CASCADE,
    url       VARCHAR(512) NOT NULL,
    position  INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX ix_review_images_review ON review_images (review_id);

CREATE TABLE review_votes
(
    review_id  BIGINT      NOT NULL REFERENCES reviews (id) ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    helpful    BOOLEAN     NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (review_id, user_id)
);

CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       VARCHAR(40)  NOT NULL,
    title      VARCHAR(160) NOT NULL,
    message    VARCHAR(500) NOT NULL,
    link       VARCHAR(255),
    read_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_notifications_user_created ON notifications (user_id, created_at DESC);
CREATE INDEX ix_notifications_user_unread ON notifications (user_id) WHERE read_at IS NULL;

CREATE TABLE search_history
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    query        VARCHAR(200) NOT NULL,
    result_count INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_search_history_user ON search_history (user_id, created_at DESC);
CREATE INDEX ix_search_history_created ON search_history (created_at DESC);

CREATE TABLE recently_viewed_products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    product_id BIGINT      NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    view_count INTEGER     NOT NULL DEFAULT 1,
    viewed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_recently_viewed_user_product UNIQUE (user_id, product_id)
);

CREATE INDEX ix_recently_viewed_user ON recently_viewed_products (user_id, viewed_at DESC);
CREATE INDEX ix_recently_viewed_product ON recently_viewed_products (product_id);
